### ISSUE TITLE
OJS 3.3.0.5: Crossref Reference Linking plugin only operates when articles are unpublished and republished

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/crossrefReferenceLinking#10]
I’m pretty sure there’s a bug in the Crossref Reference Linking plugin in 3.3.0.5 - the way it’s behaving for me right now, it only seems to do the lookup and displays the link if an article is unpublished and republished. It does not seem to do the lookup and display when an article is first published or when a new version is published. Let me explain:

One of my editors contacted me to tell me that [an article](https://refuge.journals.yorku.ca/index.php/refuge/article/view/40708) is displaying duplicate DOIs in the reference list, even though the DOIs are only listed once in the reference list metadata. Here are screenshots of the corresponding front and back end pages for that reference list:

[Back end](https://forum.pkp.sfu.ca/uploads/default/optimized/3X/f/4/f4faef6ddf1ef5d81fcd19c251c0059bc4b1d743_2_690x378.png)
[Front end](https://forum.pkp.sfu.ca/uploads/default/original/3X/0/c/0c619f9576d81b6e69f9cb16865247a7b08e5c01.png)

The editor said that she had unpublished and republished the article to make a correction (yes, it ought to have been a new version, but that’s beside the point), and that’s when the duplicate DOIs appeared.

I was able to replicate the problem by unpublishing and republishing another article. I unpublished and republished [Version 1](https://refuge.journals.yorku.ca/index.php/refuge/article/view/40660/version/1597), where you’ll see the duplicate DOIs. However, the reference for Gellner, J., & Smerek, J. (1968) only shows one DOI: in this case, the DOI was missing from the reference metadata.

When I created and published Version 2 (without making any changes to the metadata), only the DOIs that were entered in the reference metadata appeared and the DOI for the Gellner & Smerek reference no longer appeared.

This suggests to me that the DOIs are only retrieved from CrossRef and linked when the articles are unpublished and republished.

Hope this is clear, and hope I’m not missing something obvious.

**Comment by bozana** [comment]
s. https://forum.pkp.sfu.ca/t/ojs-3-3-0-5-crossref-reference-linking-plugin-only-operates-when-articles-are-unpublished-and-republished-bug/67328
The main issue was, that a Reload Scheduled Tasks of the Acon plugin was needed.

Two further issues are created to address the other issues mentioned in the post above:
https://github.com/pkp/pkp-lib/issues/7048
https://github.com/pkp/pkp-lib/issues/7047

Closing this issue...
