### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by Megazoyd** [pkp/crossrefReferenceLinking#13]
Hi, this plugin does not work. Is it because my OJS version is 3.3.0.8?
I don´t see any "check doi" button
I have to unpublish the article in order to enter references, but still doesn't work

**Comment by asmecher** [comment]
@Megazoyd, can you provide more details about what you expect? It's hard to know what you mean when you say it does not work. The issue template helps with capturing the necessary details:

**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**What application are you using?**
 OJS, OMP or OPS version X.X.X

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
