### ISSUE TITLE
plugin not working after copy to test system

### ISSUE THREAD

**Issue by bbx-github** [pkp/crossrefReferenceLinking#22]
Prior to update I copied an ojs to a test environment. Everything looks ok beside the crossrefReferenceLinking plugin. The name and description are not shown properly but the corresponding names:
##plugins.generic.crossrefReferenceLinking.displayName## and ##plugins.generic.crossrefReferenceLinking.description##

Any hints on this? Thanks in advance.
![crossref_plugin_Screenshot_20230928_220115](https://github.com/pkp/crossrefReferenceLinking/assets/53237674/a5f169a2-6b36-40bb-b43f-862a0a5ee115)

**Comment by asmecher** [comment]
@bbx-github, the support forum (https://forum.pkp.sfu.ca) is the best place to ask questions -- I'd suggest posting over there, but please also include your OJS version, the version of the CrossrefReferenceLinking plugin you're using, and how you installed it (e.g. Plugin Gallery, git checkout, uploaded as a `.tar.gz` from Github, etc).
